name: Compilar APK Android

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código do seu repositório
    - name: Baixar o código fonte
      uses: actions/checkout@v4

    # 2. Instala o Java JDK 17
    - name: Configurar o Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Fabricamos o Wrapper diretamente na versão exigida pelo plug-in 9.1.1 do seu app
    #    Instalamos o gradle base e pedimos para ele gerar o wrapper na versão 9.3.1
    - name: Instalar Gradle e Criar Wrapper 9.3.1
      run: |
        sudo apt-get update && sudo apt-get install -y gradle
        gradle wrapper --gradle-version 9.3.1

    # 4. Concede a permissão de execução para o arquivo gerado
    - name: Conceder permissão ao Gradle Wrapper
      run: chmod +x gradlew

    # 5. Executa a compilação do seu projeto
    - name: Compilar o APK de Debug
      run: ./gradlew assembleDebug

    # 6. Captura o APK gerado e disponibiliza para download
    - name: Disponibilizar APK para Download
      uses: actions/upload-artifact@v4
      with:
        name: meu-aplicativo-apk
        path: app/build/outputs/apk/debug/app-debug.apk